site_name: markov-chain-haiku
repo_url: https://github.com/jodoa002/markov-chain-haiku
site_url: https://jodoa002.github.io/markov-chain-haiku
site_description: This is an impractical Python project that makes haiku poems using markov chain analysis
site_author: Jonas Dormagen-Taraldsrud
edit_uri: edit/main/docs/
repo_name: jodoa002/markov-chain-haiku
copyright: Maintained by <a href="https://jodoa002.com">jodoa002</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/markov_chain_haiku"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jodoa002/markov-chain-haiku
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/markov-chain-haiku

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
